import os
import json
from datetime import date
import psycopg

DSN = os.getenv(
    "DATABASE_URL",
    os.getenv("DATABASE_DSN", "postgresql://postgres:indhuja@127.0.0.1:5432/kudzuops")
)

def main():
    print("🧪 Inserting one dummy CV with status=0 (waiting)...")

    with psycopg.connect(DSN) as conn:
        with conn.cursor() as cur:
            # Get an existing demand
            cur.execute("SELECT id, required_cv_count FROM tbl_demand_sheet ORDER BY id LIMIT 1")
            row = cur.fetchone()
            if not row:
                print("❌ No demand found. Create a demand first.")
                return
            demand_id, required_cv_count = row[0], row[1] or 1

            # Get a recruiter
            cur.execute("SELECT id, first_name, last_name, email FROM tbl_users WHERE role='recruiter' ORDER BY id LIMIT 1")
            r = cur.fetchone()
            recruiter_id = r[0] if r else None
            if recruiter_id is None:
                # Fallback: create a placeholder recruiter if table is empty
                cur.execute("INSERT INTO tbl_users (email, role, is_active) VALUES ('recruiter@example.com','recruiter',true) RETURNING id")
                recruiter_id = cur.fetchone()[0]

            # Create CV with proper URL
            cv = {
                "cv_id": "cv_dummy_001",
                "candidate_name": "Dummy Candidate",
                "cv_url": "Indhuja M - Exp Resume.pdf",  # Just the filename, URL will be generated by backend
                "upload_date": str(date.today()),
                "status": 0,
                "candidate_email": "dummy@example.com",
                "candidate_phone": "+10000000000",
                "experience_years": 3,
                "skills": ["Angular", "Node.js"]
            }

            # See if an activity already exists for this pair
            cur.execute("SELECT id, cv_list, uploaded_cv_count FROM tbl_recruiter_activity WHERE demand_id=%s AND recruiter_id=%s ORDER BY id LIMIT 1", (demand_id, recruiter_id))
            act = cur.fetchone()
            if act:
                act_id, cv_list, uploaded = act[0], act[1] or [], act[2] or 0
                cv_list = list(cv_list) if isinstance(cv_list, list) else []
                cv_list.append(cv)
                uploaded = uploaded + 1
                cur.execute("UPDATE tbl_recruiter_activity SET cv_list=%s, uploaded_cv_count=%s, updated_at=now() WHERE id=%s", (json.dumps(cv_list), uploaded, act_id))
                print(f"✅ Updated existing activity {act_id} with one waiting CV.")
            else:
                cur.execute(
                    """
                    INSERT INTO tbl_recruiter_activity (
                        recruiter_id, analysis_date, skill, cvs_sourced, calls_connected, recommended_profiles,
                        client_id, demand_id, uploaded_cv_count, required_cv_count, cv_list, created_at
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, now())
                    """,
                    (
                        recruiter_id, date.today(), "Angular", 1, 1, 1,
                        1, demand_id, 1, required_cv_count, json.dumps([cv])
                    )
                )
                print("✅ Inserted new activity with one waiting CV.")

            conn.commit()
            print(f"➡️ demand_id={demand_id}, recruiter_id={recruiter_id}")

if __name__ == "__main__":
    main()


